version: '3'
services:
  subconvert:
    image: womade/subconvert:latest
    container_name: subconvert
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml
